INSERT INTO USERS (USERNAME, EMAIL) VALUES ('CHEMA', 'jsmilla41@gmail.com');
INSERT INTO USERS (USERNAME, EMAIL) VALUES ('CLAUDIO', 'claudio89@gmail.com');
INSERT INTO USERS (USERNAME, EMAIL) VALUES ('PEPE', 'pepe@gmail.com');

INSERT INTO EQUIPMENTS (CODE, DESCRIPTION) VALUES ('100101', 'EQUIPO1');
INSERT INTO EQUIPMENTS (CODE, DESCRIPTION) VALUES ('100102', 'EQUIPO2');
INSERT INTO EQUIPMENTS (CODE, DESCRIPTION) VALUES ('100103', 'EQUIPO3');
INSERT INTO EQUIPMENTS (CODE, DESCRIPTION) VALUES ('100104', 'EQUIPO4');